[tool.kedro]
package_name = "phd"
project_name = "phd"
project_version = "0.18.4"

[tool.isort]
profile = "black"

#[tool.pytest.ini_options]
#addopts = """
#--cov-report term-missing \
#--cov src/phd -ra"""
#
#[tool.coverage.report]
#fail_under = 0
#show_missing = true
#exclude_lines = ["pragma: no cover", "raise NotImplementedError"]
