units = {
    'psi' : 'rad',
    'beta': 'rad',
    'delta': 'rad',
    'r': 'rad/s',
    'X_D':'N',
    'Y_D':'N',
    'N_D':'Nm',
    'X_H':'N',
    'Y_H':'N',
    'N_H':'Nm',
    'X_R':'N',
    'Y_R':'N',
    'N_R':'Nm',
    'X_P':'N',
    'Y_P':'N',
    'N_P':'Nm',
    'X_RHI':'N',
    'Y_RHI':'N',
    'N_RHI':'Nm',
    'alpha':'rad',
    'alpha_port':'rad',
    'alpha_stbd':'rad',
    'V':'m/s',
    'u':'m/s',
    'v':'m/s',
    
}